[package]
name = "uniffi-bindgen"
version = "0.26.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uniffi = { version = "0.26.1", features = ["cli"] }
